### ISSUE TITLE
Displays reporting 'api quota exceeded'

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-google-spreadsheet#321]
Instances of the widget configured to use a custom api key are exceeding the key's quota due to the combination of the configured refresh rate and number of displays showing the presentation. 

The minimum refresh interval that should be allowed when using a custom api key is 10 minutes.

**Comment by stulees** [comment]
@alanclayton I've ran a validation query to determine impact of the fix deployed from #323 . You can run query and see results [here](https://console.cloud.google.com/bigquery?sq=1088527147109:44a2a46403ea4dfc80cccd22932a0f1c).

The fix was deployed Sep 30 so Oct 1st (yesterday) is the first full day of validation. Based on the numbers from past 20 days, there is a small improvement. Usually on a Thursday the number of companies reporting is around 30. Yesterday was 18.

I think we need to go a few more business days to fully validate, so I recommend we assess this again on Tuesday Oct 6th. Thanks

**Comment by alanclayton** [comment]
@stulees could you add an action in the sos doc for this?

**Comment by stulees** [comment]
@alanclayton Will do

**Comment by alanclayton** [comment]
Reporting uptime error replaced with https://github.com/Rise-Vision/widget-google-spreadsheet/issues/324
