### ISSUE TITLE
Widget Settings incorrectly saying "sheet must be public" 

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-google-spreadsheet#322]
Details in [this doc](https://docs.google.com/document/d/1N4qg12OsgvLMnvBlD8UGYuKBcOAp89WafVS0w9Dts90/edit)

**Comment by stulees** [comment]
Apps was targeting a location on GCS for the Widget settings that is not where the widget currently deploys to, this has now been resolved.

**Comment by stulees** [comment]
@alanclayton This has been resolved. The list of websites that we allow our Sheets API key to accept requests from needs to be exactly a _Referrer_ value in the request, so we needed to now add `*/s3.amazonaws.com/* ` explicitly. We already had `*s3.amazonaws.com/widget-google-spreadsheet/*`  but this is not recognized as a Referrer.

**Comment by alanclayton** [comment]
@stulees how are you validating the correction?

**Comment by stulees** [comment]
@alanclayton I validated against the presentations you listed in the doc you provided as well as my own presentations.

**Comment by alanclayton** [comment]
Thanks. Can you tell me the uptime error associated with this error so I know for future analysis?

**Comment by stulees** [comment]
@alanclayton The `event` is _"error"_ and the `event_details` is _"spreadsheet not public"_. Are you good to close this issue now?

**Comment by alanclayton** [comment]
@stulees shouldn't this be logged as a different error since it had nothing to do with the spreadsheet?

**Comment by stulees** [comment]
@alanclayton In this situation the API was responding with an error and the status 403. This is the same error status code  returned from the API when the spreadsheet is not public. We are not able to determine the difference between these two cases, we only go by the status code. The overwhelming majority of the time a 403 error status from the API is because the spreadsheet is not public.

**Comment by alanclayton** [comment]
@stulees Thanks. For those reporting spreadsheet not public. How many are due to the Referrer issue versus the spreadsheet not being public?

**Comment by stulees** [comment]
@alanclayton We are not able to determine the difference between these two cases as they both return a 403 status code.

**Comment by alanclayton** [comment]
@stulees so how do you know the overwhelming majority of the time it is due to spreadsheet not being public?

**Comment by stulees** [comment]
@alanclayton The 403 status has indicated the spreadsheet is not public since this Widget was built. We never used to encounter any other type of error with a 403 status code, that is why we have always displayed the message for the user to inform them to make their spreadsheet public when this error has been handled. This new issue (now resolved) is recent and the first time the 403 status meant something else, so that's what I meant about "overwhelming majority of the time".

**Comment by alanclayton** [comment]
@stulees let's review tomorrow am. Thanks

**Comment by alanclayton** [comment]
@stulees this should remain open until we are informing the user and providing correction. Thanks!
